# 填写你的MAA的copilot cache路径
MAA_config_path: "D:\\MAA-v5.8.1-win-x64\\cache\\copilot"
# 填写你要替换的干员
# - 规则：
  # 字典的key是要替换的干员，格式："干员名:干员技能编号",干员技能编号为*代表所有技能。
  # 字典的value是替换后的干员，格式:"干员名:干员技能编号:干员技能使用方法编号"。
  # 如果要替换的干员已经在作业中了，不会执行任何操作。
  # 脚本执行顺序由上往下，由左往右。
  # 不要填写你没有的干员，不然会炸鸡。
upper_replace:
  # 这里是高级替换：
  # - 只会替换组（groups）内的干员。
  # - 会把组内的原有的干员直接删除并替换为指定干员。
  # e.g.:
  "临光:*": "黍:1:0"
normal_replace:
  # 普通替换
  # - 对于在opers内的单个干员，会把干员名在整个文件内执行替换。
  # - 对于在groups内的干员，如果要替换的干员在某个组内，会向这个组内**添加**目标替换干员，**不会删除原有组内干员**。
  # e.g.:
  "闪灵:*": "流明:3:1"
  "能天使:*": "艾拉:3:1"
  "星熊:*": "黍:1:0"
powerful_opers:
  # 强力干员，增加容错
  # 格式:"干员名:干员技能编号:干员技能使用方法编号"
  # 如果干员总数超过12，不会执行任何操作。
  # e.g.:
  ["维什戴尔:3:1"]
extra_opers:
  # 挂件列表
  # 只需要名字
  # 如果干员总数超过12，不会执行任何操作。
  # e.g.:
  ["德克萨斯","黍","银灰"]
